import jsPDF from 'jspdf';
import type { SiteDiary } from './types';

const BLUE: [number, number, number] = [37, 99, 235];
const DARK: [number, number, number] = [26, 20, 16];
const MUTED: [number, number, number] = [110, 95, 80];
const LIGHT_LINE: [number, number, number] = [220, 210, 200];

export function generateDiaryPDF(diary: Partial<SiteDiary>): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;

  const checkY = (needed: number) => {
    if (y + needed > pageH - margin - 8) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  };

  const addFooter = () => {
    const fY = pageH - 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(diary.date || '', margin, fY);
    doc.text('Generated by FredConSol Site Diary', pageW / 2, fY, { align: 'center' });
    doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageW - margin, fY, { align: 'right' });
  };

  const sectionHeader = (title: string) => {
    checkY(18);
    y += 4;
    doc.setFillColor(...BLUE);
    doc.rect(margin, y - 5, 3, 11, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...DARK);
    doc.text(title, margin + 7, y + 2);
    y += 10;
    doc.setDrawColor(...LIGHT_LINE);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 6;
  };

  const infoRow = (label: string, value: string) => {
    if (!value) return;
    checkY(7);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(label.toUpperCase(), margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(value, contentW - 48);
    doc.text(lines, margin + 48, y);
    y += Math.max(6, lines.length * 5);
  };

  const bullet = (text: string) => {
    const lines = doc.splitTextToSize(text, contentW - 8);
    checkY(lines.length * 5 + 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...DARK);
    doc.text('•', margin + 2, y);
    doc.text(lines, margin + 8, y);
    y += lines.length * 5 + 1;
  };

  const subHeading = (text: string) => {
    checkY(10);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(text.toUpperCase(), margin, y);
    y += 6;
  };

  // ── Cover header bar ──────────────────────────────────────
  doc.setFillColor(...BLUE);
  doc.rect(0, 0, pageW, 36, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text('FredConSol', margin, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('Site Diary', margin, 21);

  // ── Project title ─────────────────────────────────────────
  y = 50;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...DARK);
  doc.text(diary.projectName || 'Site Diary', margin, y);

  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  if (diary.siteAddress) { doc.text(diary.siteAddress, margin, y); y += 6; }
  if (diary.date) { doc.text(diary.date, margin, y); y += 6; }
  if (diary.linkedRamsRef) {
    doc.setTextColor(...BLUE);
    doc.text(`RAMS: ${diary.linkedRamsRef}`, margin, y);
    y += 6;
  }

  y += 4;
  doc.setDrawColor(...BLUE);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentW, y);
  y += 10;

  // ── Summary info ──────────────────────────────────────────
  const weather = diary.weather;
  infoRow('Site Manager', diary.siteManager || '');
  infoRow('Shift Type', diary.shiftType || '');
  infoRow('Weather', weather?.notApplicable ? 'N/A' : (weather?.condition || ''));
  if (weather?.additionalRemarks) infoRow('Weather Remarks', weather.additionalRemarks);
  if (diary.newInductees !== undefined && diary.newInductees > 0) infoRow('New Inductees', String(diary.newInductees));

  // ── Labour ────────────────────────────────────────────────
  const hasLabour = (diary.workers?.length ?? 0) + (diary.subcontractors?.length ?? 0) + (diary.visitors?.length ?? 0) > 0;
  if (hasLabour) {
    sectionHeader('Labour & Personnel');
    if (diary.workers?.length) {
      subHeading('Workers');
      for (const w of diary.workers) bullet(`${w.trade} — ${w.numberOfWorkers} worker(s) — ${w.company}`);
      y += 2;
    }
    if (diary.subcontractors?.length) {
      subHeading('Subcontractors');
      for (const s of diary.subcontractors) bullet(`${s.trade} — ${s.numberOfWorkers} worker(s) — ${s.company}`);
      y += 2;
    }
    if (diary.visitors?.length) {
      subHeading('Visitors');
      for (const v of diary.visitors) bullet(`${v.name} (${v.company}) — ${v.purpose}`);
    }
  }

  // ── Work Activities ───────────────────────────────────────
  if ((diary.activities?.length ?? 0) + (diary.milestones?.length ?? 0) > 0) {
    sectionHeader('Work Activities');
    if (diary.activities?.length) {
      for (const a of diary.activities) bullet(a.description);
      y += 2;
    }
    if (diary.milestones?.length) {
      subHeading('Milestones');
      for (const m of diary.milestones) bullet(m);
    }
  }

  // ── Plant & Materials ─────────────────────────────────────
  const hasPlant =
    (diary.plantOnSite?.length ?? 0) +
    (diary.plantOffHired?.length ?? 0) +
    (diary.plantBreakdowns?.length ?? 0) +
    (diary.plantDeliveries?.length ?? 0) > 0;
  if (hasPlant) {
    sectionHeader('Plant & Materials');
    if (diary.plantOnSite?.length) {
      subHeading('On Site');
      for (const p of diary.plantOnSite) {
        let text = p.item;
        if (p.supplier) text += ` — ${p.supplier}`;
        if (p.issue) text += ` ⚠ Issue: ${p.issue}`;
        bullet(text);
      }
      y += 2;
    }
    if (diary.plantOffHired?.length) {
      subHeading('Off Hired');
      for (const p of diary.plantOffHired) bullet(`${p.item} — ${p.date}${p.notes ? ` — ${p.notes}` : ''}`);
      y += 2;
    }
    if (diary.plantBreakdowns?.length) {
      subHeading('Breakdowns');
      for (const p of diary.plantBreakdowns) bullet(`${p.item}: ${p.issue}${p.actionTaken ? ` — Action: ${p.actionTaken}` : ''}`);
      y += 2;
    }
    if (diary.plantDeliveries?.length) {
      subHeading('Deliveries');
      for (const p of diary.plantDeliveries) bullet(`${p.item} — ${p.date}${p.notes ? ` — ${p.notes}` : ''}${(p.photoUrls?.length ?? 0) > 0 ? ` (${p.photoUrls!.length} photo${p.photoUrls!.length !== 1 ? 's' : ''})` : ''}`);
    }
  }

  // ── Health & Safety ───────────────────────────────────────
  if ((diary.incidents?.length ?? 0) + (diary.toolboxTalks?.length ?? 0) > 0) {
    sectionHeader('Health & Safety');
    if (diary.incidents?.length) {
      subHeading('Incidents');
      for (const i of diary.incidents) {
        let text = `[${i.type.toUpperCase()}] ${i.description}`;
        if (i.injured) text += ` — Injured: ${i.injured}`;
        if (i.actionTaken) text += ` — Action: ${i.actionTaken}`;
        bullet(text);
      }
      y += 2;
    }
    if (diary.toolboxTalks?.length) {
      subHeading('Toolbox Talks');
      for (const t of diary.toolboxTalks) {
        bullet(t.remarks ? `${t.topic} — ${t.remarks}` : t.topic);
      }
    }
  }

  // ── Notes ─────────────────────────────────────────────────
  if (diary.notes) {
    sectionHeader('Additional Notes');
    const lines = doc.splitTextToSize(diary.notes, contentW);
    checkY(lines.length * 5 + 2);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...DARK);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 4;
  }

  // ── Sign-off ──────────────────────────────────────────────
  if (diary.signoff?.signatureUrl) {
    sectionHeader('Sign-off');
    checkY(36);
    try {
      const sigData = diary.signoff.signatureUrl;
      const format = sigData.startsWith('data:image/png') ? 'PNG' : 'JPEG';
      doc.addImage(sigData, format, margin, y, 70, 24);
      y += 28;
    } catch {
      // signature embed failed — skip silently
    }
    doc.setDrawColor(...LIGHT_LINE);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + 70, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text('Site Manager Signature', margin, y);
  }

  // ── Footers on all pages ──────────────────────────────────
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const fY = pageH - 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(diary.date || '', margin, fY);
    doc.text('Generated by FredConSol Site Diary', pageW / 2, fY, { align: 'center' });
    doc.text(`Page ${i} of ${total}`, pageW - margin, fY, { align: 'right' });
  }

  const safeName = (diary.projectName || 'diary').replace(/[^a-z0-9]/gi, '-').toLowerCase();
  doc.save(`site-diary-${safeName}-${diary.date || 'export'}.pdf`);
}
