import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { SiteDiary } from './types';

// ── Colour palette ────────────────────────────────────────────────
const C = {
  accent:      [37,  99,  235] as [number, number, number],
  white:       [255, 255, 255] as [number, number, number],
  textDark:    [20,  20,  20]  as [number, number, number],
  textMid:     [80,  80,  80]  as [number, number, number],
  borderLight: [210, 215, 220] as [number, number, number],
  labelCell:   [226, 232, 240] as [number, number, number],
  tableHead:   [200, 210, 220] as [number, number, number],
  headerFill:  [36,  27,  21]  as [number, number, number],
  alertRed:    [220, 38,  38]  as [number, number, number],
};

const FONT   = 'helvetica';
const MARGIN = 18;

// ── UK date helper ────────────────────────────────────────────────
const toUKDate = (d?: string): string => {
  if (!d) return '';
  if (d.includes('/')) return d;
  if (d.includes('-')) {
    const [y, m, dd] = d.split('-');
    return `${dd}/${m}/${y}`;
  }
  return d;
};

// ── Section header — matches RAMS sectionHeader() style ───────────
function sectionHeader(doc: jsPDF, title: string, y: number): number {
  const pw = doc.internal.pageSize.getWidth();
  const cw = pw - MARGIN * 2;
  if (y > doc.internal.pageSize.getHeight() - 30) {
    doc.addPage('a4', 'portrait');
    y = MARGIN;
  }
  doc.setFont(FONT, 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...C.textDark);
  doc.text(title.toUpperCase(), MARGIN, y + 8);
  doc.setDrawColor(...C.accent);
  doc.setLineWidth(1.5);
  doc.line(MARGIN, y + 11, MARGIN + cw, y + 11);
  doc.setDrawColor(...C.borderLight);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y + 12.5, MARGIN + cw, y + 12.5);
  doc.setTextColor(...C.textDark);
  return y + 18;
}

// ── Sub-header — accent left tab + dark fill ──────────────────────
function subHeader(doc: jsPDF, title: string, y: number): number {
  const pw = doc.internal.pageSize.getWidth();
  const cw = pw - MARGIN * 2;
  doc.setFillColor(...C.accent);
  doc.rect(MARGIN, y, 3, 6, 'F');
  doc.setFillColor(...C.headerFill);
  doc.rect(MARGIN + 3, y, cw - 3, 6, 'F');
  doc.setFont(FONT, 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...C.white);
  doc.text(title.toUpperCase(), MARGIN + 7, y + 4.3);
  doc.setTextColor(...C.textDark);
  return y + 9;
}

// ── Page footers ──────────────────────────────────────────────────
function addFooters(doc: jsPDF, diary: Partial<SiteDiary>): void {
  const total = doc.getNumberOfPages();
  const pw    = doc.internal.pageSize.getWidth();
  const ph    = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const fy = ph - 8;
    doc.setDrawColor(...C.borderLight);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, fy - 3, pw - MARGIN, fy - 3);
    doc.setFont(FONT, 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...C.textMid);
    doc.text(toUKDate(diary.date) || '', MARGIN, fy);
    doc.text('Generated by FredConSol Site Diary', pw / 2, fy, { align: 'center' });
    doc.text(`Page ${i} of ${total}`, pw - MARGIN, fy, { align: 'right' });
  }
}

// ── Table shared styles ───────────────────────────────────────────
const TABLE_STYLES = {
  fontSize:    8.5,
  cellPadding: 2.5,
  lineColor:   [210, 215, 220] as [number, number, number],
  lineWidth:   0.2,
  valign:      'top' as const,
};

const HEAD_STYLES = {
  fillColor:  C.tableHead,
  textColor:  C.textDark,
  fontStyle:  'bold' as const,
  fontSize:   8.5,
  cellPadding: 2.5,
};

const LABEL_STYLE = { fontStyle: 'bold' as const, fillColor: C.labelCell };

// ── Main export ───────────────────────────────────────────────────
export function generateDiaryPDF(diary: Partial<SiteDiary>): void {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw   = doc.internal.pageSize.getWidth();
  const ph   = doc.internal.pageSize.getHeight();
  const cw   = pw - MARGIN * 2;
  let y      = MARGIN;

  // Helper: get y after last autoTable
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const autoY = (): number => (doc as any).lastAutoTable?.finalY ?? y;

  // ── Cover header bar ──────────────────────────────────────
  doc.setFillColor(...C.accent);
  doc.rect(0, 0, pw, 38, 'F');
  doc.setFont(FONT, 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...C.white);
  doc.text('FredConSol', MARGIN, 15);
  doc.setFont(FONT, 'normal');
  doc.setFontSize(8.5);
  doc.text('Site Diary', MARGIN, 22);
  doc.text(toUKDate(diary.date) || '', pw - MARGIN, 22, { align: 'right' });

  // ── Project title ─────────────────────────────────────────
  y = 50;
  doc.setFont(FONT, 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...C.textDark);
  doc.text(diary.projectName || 'Site Diary', MARGIN, y);
  y += 8;

  doc.setFont(FONT, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  if (diary.siteAddress) { doc.text(diary.siteAddress, MARGIN, y); y += 6; }
  if (diary.date)        { doc.text(toUKDate(diary.date), MARGIN, y); y += 6; }
  if (diary.linkedRamsRef) {
    doc.setTextColor(...C.accent);
    doc.text(`RAMS Ref: ${diary.linkedRamsRef}`, MARGIN, y);
    y += 6;
  }
  if (diary.linkedRamsTitle) {
    doc.setTextColor(100, 100, 100);
    doc.text(diary.linkedRamsTitle, MARGIN, y);
    y += 6;
  }

  y += 3;
  doc.setDrawColor(...C.accent);
  doc.setLineWidth(0.8);
  doc.line(MARGIN, y, MARGIN + cw, y);
  y += 8;

  // ── Summary info table ────────────────────────────────────
  const weather = diary.weather;
  const weatherStr = weather?.notApplicable ? 'N/A' : (weather?.condition || '—');
  const summaryRows: [string, string][] = [
    ['Site Manager', diary.siteManager || '—'],
    ['Shift Type',   diary.shiftType   || '—'],
    ['Weather', weather?.additionalRemarks
      ? `${weatherStr} — ${weather.additionalRemarks}`
      : weatherStr],
  ];
  if (diary.newInductees && diary.newInductees > 0) {
    summaryRows.push(['New Inductees Today', String(diary.newInductees)]);
  }

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    body:   summaryRows,
    columnStyles: { 0: { ...LABEL_STYLE, cellWidth: 50 } },
    styles: TABLE_STYLES,
    theme:  'grid',
  });
  y = autoY() + 10;

  // ── Labour & Personnel ────────────────────────────────────
  const hasLabour =
    (diary.workers?.length ?? 0) +
    (diary.subcontractors?.length ?? 0) +
    (diary.visitors?.length ?? 0) > 0;

  if (hasLabour) {
    y = sectionHeader(doc, 'Labour & Personnel', y);

    if (diary.workers?.length) {
      y = subHeader(doc, 'Workers', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Trade', 'No. Workers', 'Company']],
        body:       diary.workers.map((w) => [w.trade, String(w.numberOfWorkers), w.company]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.subcontractors?.length) {
      y = subHeader(doc, 'Subcontractors', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Trade', 'No. Workers', 'Company']],
        body:       diary.subcontractors.map((s) => [s.trade, String(s.numberOfWorkers), s.company]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.visitors?.length) {
      y = subHeader(doc, 'Visitors', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Name', 'Company', 'Purpose']],
        body:       diary.visitors.map((v) => [v.name, v.company, v.purpose]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 10;
    }
  }

  // ── Work Activities ───────────────────────────────────────
  if ((diary.activities?.length ?? 0) + (diary.milestones?.length ?? 0) > 0) {
    y = sectionHeader(doc, 'Work Activities', y);

    if (diary.activities?.length) {
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Activity Description']],
        body:       diary.activities.map((a) => [a.description]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.milestones?.length) {
      y = subHeader(doc, 'Milestones', y);
      autoTable(doc, {
        startY: y,
        margin: { left: MARGIN, right: MARGIN },
        body:   diary.milestones.map((m) => [m]),
        styles: TABLE_STYLES,
        theme:  'grid',
      });
      y = autoY() + 10;
    }
  }

  // ── Plant & Materials ─────────────────────────────────────
  const hasPlant =
    (diary.plantOnSite?.length ?? 0) +
    (diary.plantOffHired?.length ?? 0) +
    (diary.plantBreakdowns?.length ?? 0) +
    (diary.plantDeliveries?.length ?? 0) > 0;

  if (hasPlant) {
    y = sectionHeader(doc, 'Plant & Materials', y);

    if (diary.plantOnSite?.length) {
      y = subHeader(doc, 'Plant On Site', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Item', 'Supplier', 'Issue']],
        body:       diary.plantOnSite.map((p) => [
          p.item,
          p.supplier || '—',
          p.issue
            ? { content: p.issue, styles: { textColor: C.alertRed } }
            : '—',
        ]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.plantOffHired?.length) {
      y = subHeader(doc, 'Plant Off-Hired', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Item', 'Date', 'Notes']],
        body:       diary.plantOffHired.map((p) => [p.item, toUKDate(p.date), p.notes || '—']),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.plantBreakdowns?.length) {
      y = subHeader(doc, 'Breakdowns', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Item', 'Issue', 'Action Taken']],
        body:       diary.plantBreakdowns.map((p) => [p.item, p.issue, p.actionTaken || '—']),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 6;
    }

    if (diary.plantDeliveries?.length) {
      y = subHeader(doc, 'Deliveries', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Item', 'Date', 'Notes', 'Photos']],
        body:       diary.plantDeliveries.map((p) => [
          p.item,
          toUKDate(p.date),
          p.notes || '—',
          p.photoUrls?.length
            ? `${p.photoUrls.length} photo${p.photoUrls.length !== 1 ? 's' : ''}`
            : '—',
        ]),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 10;
    }
  }

  // ── Health & Safety ───────────────────────────────────────
  if ((diary.incidents?.length ?? 0) + (diary.toolboxTalks?.length ?? 0) > 0) {
    y = sectionHeader(doc, 'Health & Safety', y);

    if (diary.incidents?.length) {
      y = subHeader(doc, 'Incidents & Near-Misses', y);
      autoTable(doc, {
        startY:        y,
        margin:        { left: MARGIN, right: MARGIN },
        head:          [['Type', 'Description', 'Injured Party', 'Action Taken']],
        body:          diary.incidents.map((i) => [
          i.type.toUpperCase(),
          i.description,
          i.injured    || '—',
          i.actionTaken || '—',
        ]),
        headStyles:    HEAD_STYLES,
        styles:        TABLE_STYLES,
        columnStyles:  { 0: { cellWidth: 22 } },
        theme:         'grid',
      });
      y = autoY() + 6;
    }

    if (diary.toolboxTalks?.length) {
      y = subHeader(doc, 'Toolbox Talks', y);
      autoTable(doc, {
        startY:     y,
        margin:     { left: MARGIN, right: MARGIN },
        head:       [['Topic', 'Remarks']],
        body:       diary.toolboxTalks.map((t) => [t.topic, t.remarks || '—']),
        headStyles: HEAD_STYLES,
        styles:     TABLE_STYLES,
        theme:      'grid',
      });
      y = autoY() + 10;
    }
  }

  // ── Additional Notes ──────────────────────────────────────
  if (diary.notes) {
    y = sectionHeader(doc, 'Additional Notes', y);
    const lines = doc.splitTextToSize(diary.notes, cw);
    if (y + lines.length * 5 + 4 > ph - 18) {
      doc.addPage('a4', 'portrait');
      y = MARGIN;
    }
    doc.setFont(FONT, 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...C.textDark);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5 + 8;
  }

  // ── Sign-off ──────────────────────────────────────────────
  if (diary.signoff?.signatureUrl) {
    y = sectionHeader(doc, 'Sign-off', y);
    if (y + 36 > ph - 18) { doc.addPage('a4', 'portrait'); y = MARGIN; }
    try {
      const sigData = diary.signoff.signatureUrl;
      const format  = sigData.startsWith('data:image/png') ? 'PNG' : 'JPEG';
      doc.addImage(sigData, format, MARGIN, y, 70, 24);
      y += 28;
    } catch {
      // signature embed failed — skip silently
    }
    doc.setDrawColor(...C.borderLight);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, MARGIN + 70, y);
    y += 5;
    doc.setFont(FONT, 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...C.textMid);
    doc.text('Site Manager Signature', MARGIN, y);
  }

  // ── Footers on all pages ──────────────────────────────────
  addFooters(doc, diary);

  // ── File name ─────────────────────────────────────────────
  const parsedDate = new Date(diary.date || '');
  const dd      = String(parsedDate.getDate()).padStart(2, '0');
  const mm      = String(parsedDate.getMonth() + 1).padStart(2, '0');
  const yy      = String(parsedDate.getFullYear()).slice(-2);
  const dateStr = isNaN(parsedDate.getTime()) ? (diary.date || 'export') : `${dd}${mm}${yy}`;
  const ramsRef = diary.linkedRamsRef ? `_${diary.linkedRamsRef}` : '';
  const projName = (diary.projectName || 'SiteDiary').replace(/[^a-zA-Z0-9]/g, '_');
  doc.save(`${projName}_${dateStr}${ramsRef}.pdf`);
}
